# Notice: This template has only been tested 
# under Python27 + GAE standard environment
application: clock-170302
version: 1
runtime: python27
# threadsafe is required but can be either true or 
# false. For some package, it should be true e.g. Flask
threadsafe: true
api_version: 1

service: default

handlers:
  - url: /favicion\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /js
    static_dir: static/js

  - url: /css
    static_dir: static/css

  - url: /img
    static_dir: static/img

  - url: /.*
    script: server.main.app

libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest
  